[package]
name = "app-icon-preview"
version = "2.1.2"
authors = ["Bilal Elmoussaoui <bilal.elmoussaoui@gnome.org>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
gtk = { package = "gtk4", version = "0.3" }
gdk_pixbuf = { package = "gdk-pixbuf", version = "0.14", features = ["v2_36"]}
log = "0.4"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk-macros = "0.3"
adw = { package = "libadwaita", version = "0.1.0-alpha-5" }
pangocairo = "0.14"
pretty_env_logger = "0.3"
cairo = { package = "cairo-rs", version = "0.14", features = ["svg", "v1_16"]}
rand = "0.7"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
svgcleaner = "0.9"
anyhow = "1.0"
once_cell = "1.4"

[dependencies.rsvg]
package = "librsvg"
git = "https://gitlab.gnome.org/gnome/librsvg"
version = "2.51"
